"""The key=value fixture format the Rust tests read, and the provenance note every header carries."""


def render(header, blocks):
    """Renders a fixture: `# `-prefixed header lines, then one block per case.

    `blocks` is a sequence of `(prefix, comment, case)`; every entry of `case` becomes a line
    `<prefix>_<key>=<repr(value)>`. Values are floats, dates included, because that is what the
    Rust side parses.
    """
    lines = [f"# {line}".rstrip() for line in header]
    for prefix, comment, case in blocks:
        lines.append("")
        if comment:
            lines.append(f"# {comment}")
        for key, value in case.items():
            lines.append(f"{prefix}_{key}={value!r}")
    return "\n".join(lines) + "\n"


def provenance(module):
    """Header lines naming where a fixture's values come from."""
    return [
        f"Generated by reference/generate.py from reference/kestrel_reference/fixtures/{module}.py:",
        "an independent second implementation written from the documented formulas, using the",
        "Python standard library only. `python3 reference/generate.py` regenerates this file;",
        "`python3 reference/generate.py --check` verifies it byte for byte.",
    ]


def date_keys(prefix, day):
    """A date as the three float keys `<prefix>_y`, `<prefix>_m`, `<prefix>_d`."""
    return {
        f"{prefix}_y": float(day.year),
        f"{prefix}_m": float(day.month),
        f"{prefix}_d": float(day.day),
    }
